author: Paul Jenkins
url: https://www.tmwlvrn.com
#logo: /assets/images/home-blog-card.png
social:
  name: tmuWolverine
  links:
    - https://github.com/temuwolverine
    - https://www.youtube.com/@tmuWolverine
locale : en_au
title: "tmuWolverine"
logo: /assets/images/logo.png
picture: 
  ignore_missing_images: true
sass:
  sourcemap: never

plugins:
  - jekyll-toc  
  - jekyll-seo-tag
postcss:
  cache: false
  minify: true

exclude:
  - .gitignore
  - bin
  - node_modules
  - package-lock.json
  - postcss.config.js
  - README.md
  # - assets/css/tailwind.scss

# files Jekyll should not delete from .site
keep_files:
  - assets/css/tailwind.css
  - assets/css/tailwind.css.map